sudo: false  # run on new infrastructure
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - "3.10-dev"
  - "nightly"
  - "pypy3"
env:
  - UNIT_TESTS=true
  - STYLE_TESTS=true
  - CHECK_MANIFEST=true
  - DOC_BUILD=true
matrix:
  allow_failures:
    - python: "pypy3"
    - python: "nightly"
    - env: STYLE_TESTS=true
  fast_finish: true
  exclude:
    - env: STYLE_TESTS=true
    - env: CHECK_MANIFEST=true
    - env: DOC_BUILD=true
  include:
    - python: 3.9
      env: STYLE_TESTS=true
    - python: 3.9
      env: CHECK_MANIFEST=true
    - python: 3.9
      env: DOC_BUILD=true
# Cache Dependencies
cache: pip
before_install:
  - if [ "$UNIT_TESTS" = "true" ]; then
      echo "Running Unit Tests";
    fi
  - if [ "$STYLE_TESTS" = "true" ]; then
      echo "Running Code Style Tests";
    fi
  - if [ "$CHECK_MANIFEST" = "true" ]; then
      echo "Checking Manifest.in";
    fi
  - if [ "$DOC_BUILD" = "true" ]; then
      echo "Seeing if Docucemtnation Builds";
    fi
  - printenv
# command to install dependencies
install:
  - pip install --upgrade pip
  - if [ "$UNIT_TESTS" = "true" ]; then
      pip install -r .requirements/base.txt;
      pip install -r .requirements/test.txt;
      pip install coveralls;
    fi
  - if [ "$STYLE_TESTS" = "true" ]; then
      pip install -r .requirements/test.txt;
    fi
  - if [ "$CHECK_MANIFEST" = "true" ]; then
      pip install -r .requirements/test.txt;
    fi
  - if [ "$DOC_BUILD" = "true" ]; then
      pip install .;
      pip install -r .requirements/docs.txt;
    fi
before_script:
  - if [ "$UNIT_TESTS" = "true" ]; then
      green --version;
    fi
  - if [ "$STYLE_TESTS" = "true" ]; then
      isort --version;
      black --version
      pydocstyle --version;
      pycodestyle --version;
    fi
  - if [ "$CHECK_MANIFEST" = "true" ]; then
      check-manifest --version;
    fi
# command to run tests
script:
  - if [ "$UNIT_TESTS" = "true" ]; then
      green colourettu -vvr;
    fi
  - if [ "$STYLE_TESTS" = "true" ]; then
      isort colourettu setup.py tasks.py --verbose;
    fi
  - if [ "$STYLE_TESTS" = "true" ]; then
      black colourettu setup.py tasks.py --verbose --check;
    fi
  - if [ "$STYLE_TESTS" = "true" ]; then
      pydocstyle colourettu;
    fi
  - if [ "$STYLE_TESTS" = "true" ]; then
      pycodestyle colourettu;
    fi
  - if [ "$CHECK_MANIFEST" = "true" ]; then
      check-manifest --verbose;
    fi
  - if [ "$DOC_BUILD" = "true" ]; then
      sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html;
    fi
after_success:
  - if [ "$UNIT_TESTS" = "true" ]; then
      coveralls;
    fi
