language: python
python:
  # - "2.6"  # green doesn't run on Python 2.6
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install coveralls
# command to run tests
script: green tests -vvr
after_success:
  coveralls
