language: python
python:
  # - "2.6"  # green doesn't run on Python 2.6
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r tests/requirements.txt
# command to run tests
script: green tests -vv
