sudo: false  # run on new infrastructure
language: python
python:
  # - "2.6"  # green doesn't run on Python 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "nightly"
  - "pypy"
  - "pypy3"
env:
  - UNIT_TESTS=true
  - DOC_TESTS=true
matrix:
  allow_failures:
    - python: 2.7
    - python: "pypy"
    - python: "nightly"
    - env: DOC_TESTS=true
  fast_finish: true
  exclude:
    - env: DOC_TESTS=true
  include:
    - python: 3.5
      env: DOC_TESTS=true
# Cache Dependencies
cache: pip
before_install:
  - if [ "$UNIT_TESTS" = "true" ]; then
      echo "Running Unit Tests";
    fi
  - if [ "$DOC_TESTS" = "true" ]; then
      echo "Running Code Style Tests";
    fi
  - printenv
# command to install dependencies
install:
  - pip install --upgrade pip
  - if [ "$UNIT_TESTS" = "true" ]; then
      pip install -r requirements.txt;
      pip install -r tests/requirements.txt;
      pip install coveralls;
    fi
  - if [ "$DOC_TESTS" = "true" ]; then
      pip install isort pydocstyle pycodestyle;
    fi
before_script:
  - if [ "$UNIT_TESTS" = "true" ]; then
      green --version;
    fi
  - if [ "$DOC_TESTS" = "true" ]; then
      isort --version;
      pydocstyle --version;
      pycodestyle --version;
    fi
# command to run tests
script:
  - if [ "$UNIT_TESTS" = "true" ]; then
      green tests -vvr;
    fi
  - if [ "$DOC_TESTS" = "true" ]; then
      isort --recursive colourettu --verbose;
    fi
  - if [ "$DOC_TESTS" = "true" ]; then
      pydocstyle colourettu;
    fi
  - if [ "$DOC_TESTS" = "true" ]; then
      pycodestyle colourettu;
    fi
after_success:
  - if [ "$UNIT_TESTS" = "true" ]; then
      coveralls;
    fi
