sudo: false  # run on new infrastructure
language: python
python:
  # - "2.6"  # green doesn't run on Python 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "3.6-dev"
  - "pypy"
  - "pypy3"
env:
  - UNIT_TESTS=true
  - DOC_TESTS=true
matrix:
  allow_failures:
    - python: 2.7
    - python: "pypy"
    - python: "3.6-dev"
    - env: DOC_TESTS=true
  fast_finish: true
  exclude:
    - env: DOC_TESTS=true
  include:
    - python: 3.5
      env: DOC_TESTS=true
# Cache Dependencies
cache:
  directories:
    - $HOME/travis/.cache/pip
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - test $UNIT_TESTS = true \
      && pip install -r tests/requirements.txt \
      && pip install coveralls
  - test $DOC_TESTS = true \
      && pip install isort pydocstyle pycodestyle
before_script:
  - test $UNIT_TESTS = true \
      && green --version
   - test $DOC_TESTS = true \
      && isort --version
      && pydocstyle --version
      && pycodestyle --version
# command to run tests
script:
  - test $UNIT_TESTS = true \
      && green test -vvr
   - test $DOC_TESTS = true \
      && isort --recusrive colourettu --verbose
      && pydocstyle colourettu
      && pycodestyle colourettu
after_success:
  - test $UNIT_TESTS = true \
      && coveralls
